import sketch from "./sketch";

export default {
  longDescription: {
    ko: "Wang Tiles은 각 변에 색상이 할당된 정사각형 타일을 사용하여, 인접한 타일의 변 색상이 일치하도록 배치하는 알고리즘입니다. 유한한 타일 집합으로도 반복되지 않는 비주기적 패턴을 생성할 수 있으며, 이는 제약 충족 문제(constraint satisfaction)의 대표적인 예시입니다. 타일링 이론, 컴퓨터 그래픽스, 절차적 콘텐츠 생성 등에 활용됩니다.",
    en: "Wang Tiles is an algorithm that places square tiles with colored edges such that adjacent tiles have matching edge colors. Even with a finite tile set, it can generate aperiodic patterns that never repeat, serving as a classic example of constraint satisfaction problems. It is used in tiling theory, computer graphics, and procedural content generation.",
  },
  sketch,
params: [
  {
    key: 'tileSize',
    label: '타일 크기',
    min: 20,
    max: 80,
    step: 2,
    default: 40,
    unit: 'px',
    restart: true,
  },
  {
    key: 'numColorVariations',
    label: '경계 색상 수',
    min: 2,
    max: 8,
    step: 1,
    default: 3,
    restart: true,
  },
  {
    key: 'tileComplexity',
    label: '타일 종류 수',
    min: 4,
    max: 32,
    step: 1,
    default: 12,
    restart: true,
  },
  {
    key: 'gridLineAlpha',
    label: '구분선 투명도',
    min: 0,
    max: 180,
    step: 5,
    default: 80,
  },
  {
    key: 'tileOutlineWeight',
    label: '외곽선 두께',
    min: 0,
    max: 5,
    step: 0.1,
    default: 2,
  },
  {
    key: 'colorBrightness',
    label: '밝기',
    min: 0.3,
    max: 1.2,
    step: 0.05,
    default: 1.0,
    restart: true,
  },
],
  related: ["Truchet Tiles", "Wave Function Collapse", "Circle Packing"],
};