import sketch from './sketch'

export default {
  longDescription: {
    ko: String.raw`
**Penrose Tiling**(펜로즈 타일링)은 두 종류의 **마름모(Rhombus, 굵은 마름모와 가는 마름모)** 만을 사용하여 평면을 비주기적으로 완전히 덮는 타일링 패턴입니다. **황금비(Golden Ratio)** $\phi = \frac{1+\sqrt{5}}{2}$를 기반으로 한 **분할 규칙(Inflation Rules)** 을 반복 적용하면, 원자적 규칙성이 없으면서도 국소적으로는 엄격한 타일 결합 제약을 만족하는 무한히 복잡한 구조가 생성됩니다. **Roger Penrose**가 1974년 발견한 이 패턴은 수학, 물리, 예술의 교집합에서 가장 흥미로운 사례이며, 자연계의 준결정체(Quasicrystal) 구조에서도 발견됩니다.

### 1. 핵심 수학적 원리
1. **두 마름모의 정의:**
   - **Thick Rhombus (굵은 마름모):** 예각 $72°$, 둔각 $108°$
   - **Thin Rhombus (가는 마름모):** 예각 $36°$, 둔각 $144°$
   - 두 마름모 모두 대각선 길이 비가 황금비 $\phi = 1.618...$

2. **황금비의 역할:**
   - 마름모의 변 길이: $a$와 $b$에 대해 $a/b = \phi$
   - 대각선 길이도 황금비로 결정
   - 이 비율이 타일들이 완벽히 결합되기 위한 필수 조건

3. **분할 규칙(Inflation):**
   - Thick Rhombus는 1개의 Thick + 1개의 Thin으로 분할
   - Thin Rhombus는 1개의 Thick + 2개의 Thin으로 분할
   - 각 분할 후 마름모의 변의 길이는 $1/\phi$로 축소
   - 이 규칙을 $n$번 반복 적용하면 크기가 $1/\phi^n$로 축소된 타일들이 채워짐

4. **De Bruijn 방법:**
   - 5차원 격자의 단면으로 Penrose Tiling을 기하학적으로 구성하는 이론
   - 이는 Penrose Tiling의 비주기성이 수학적으로 본질적임을 증명

### 2. 주요 특징 및 장점
- **비주기성(Aperiodicity):** 반복 대칭이 없으면서도 어떤 방향으로도 평행이동할 수 없지만, 국소 패턴은 엄격하게 정의됨.
- **황금비의 무한 출현:** 어디를 보든 황금비 관계가 드러나며, 이는 자연의 미적 조화와 깊은 연관.
- **비결정체(Quasicrystal) 모델:** 1982년 발견된 실제 금속 합금(Al-Mn)의 원자 배열이 Penrose Tiling과 동일 구조.
- **계산 자동화:** 분할 규칙이 명확해서, 컴퓨터로 무한히 복잡한 패턴을 자동 생성 가능.

### 3. 구현 시 고려 사항
- **마름모 좌표 표현:** 각 마름모의 위치와 방향을 추적하기 위해 벡터 기반 표현 사용.
- **분할 재귀 깊이 제한:** 이론적으로 무한이지만, 실제 렌더링을 위해 적절한 깊이(보통 6~8 세대)로 제한.
- **중복 제거:** 분할 후 경계에서 겹치는 타일을 정확히 처리하여 중복 렌더링 방지.
- **색상 할당 전략:** 세대별, 타일 종류별로 다른 색상 부여하여 구조를 시각적으로 강조.

### 4. 활용 분야
- **순수 수학 탐구:** 기하학, 위상수학, 준결정체 이론의 구체적 사례.
- **재료과학:** 준결정 구조 연구, 새로운 물질의 물리적 성질 예측.
- **Generative Art:** 황금비와 비주기성의 미적 표현, 시각적 조화의 탐험.
- **건축 & 디자인:** 타일 패턴, 의류 도안, 장식 모티프로의 적용.
- **교육:** 대칭, 비주기성, 황금비, 기하학적 분할 등의 고급 개념 시각화.
    `,
    en: String.raw`
Penrose Tiling is a remarkable non-periodic tiling of the plane using only two types of rhombuses (thick and thin). Generated by repeatedly applying inflation rules based on the golden ratio φ ≈ 1.618, it covers the plane without periodicity yet with strict local matching rules. Discovered by Roger Penrose in 1974, it is a profound example at the intersection of mathematics, physics, and art — and similar structures have been discovered in real quasicrystal materials, demonstrating deep connections between abstract mathematics and physical reality.
    `,
  },
  sketch,
  params: [
    { 
      key: 'generations', 
      label: '분할 세대 수', 
      min: 1, 
      max: 4, 
      step: 1, 
      default: 2, 
      restart: true 
    },
    { 
      key: 'initialRadius', 
      label: '초기 반지름 비율', 
      min: 0.2, 
      max: 0.6, 
      step: 0.01, 
      default: 0.35, 
      restart: true 
    },
    { 
      key: 'goldenRatio', 
      label: '황금비 - 1.618', 
      min: 1.4, 
      max: 1.8, 
      step: 0.001, 
      default: 1.618, 
      restart: true 
    },
    { 
      key: 'lineWeight', 
      label: '경계선 굵기', 
      min: 0, 
      max: 3, 
      step: 0.1, 
      default: 0.2 
    },
    { 
      key: 'rotationSpeed', 
      label: '회전 속도', 
      min: -0.02, 
      max: 0.02, 
      step: 0.001, 
      default: 0.001 
    },
  ],
  related: ['IFS & Fractal', 'Truchet Tiles', 'Wang Tiles'],
}